<?php

/* 
 * This class is used to log Events generated by the system at the system
 */

class Log{
    public function __construct($message) {

        $filepath = __SITE_PATH . "/logs/logs.txt";
        $date = new DateTime('now', new DateTimeZone('Europe/London'));
        $newMessage = $date->format('Y-m-d');
        $newMessage = $newMessage . "   :   " . $message . "\r\n";

        //dump log to file;
        file_put_contents($filepath, $newMessage, FILE_APPEND);
    }
}

